# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dest', models.CharField(max_length=255)),
                ('planned_by', models.CharField(max_length=255)),
                ('date_from', models.DateTimeField()),
                ('date_to', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('travelers', models.ManyToManyField(related_name='users_on_trip', to='user_app.User')),
            ],
        ),
    ]
