# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='dest',
            new_name='desc',
        ),
    ]
