# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-26 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0003_auto_20180126_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateField(auto_now_add=True),
        ),
    ]
